CREATE TABLE IF NOT EXISTS watch_statuses (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS movies (
    id SERIAL PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    director VARCHAR(120) NOT NULL,
    release_year INTEGER NOT NULL CHECK (release_year >= 1888),
    status_id INTEGER NOT NULL REFERENCES watch_statuses(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id SERIAL PRIMARY KEY,
    movie_id INTEGER NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    author VARCHAR(100) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 10),
    text TEXT NOT NULL,
    reviewed_at DATE NOT NULL DEFAULT CURRENT_DATE
);
